app/blueprints/patrols/__init__.py
from flask import Blueprint

bp = Blueprint("patrols", __name__)

from app.blueprints.patrols import routes

__all__ = [
    "bp",
    "routes",
]

app/blueprints/patrols/routes.py
from flask import render_template
from app.blueprints.patrols import bp
from app.models import Group, Requirement, Rank


@bp.route("/")
def index():
    return render_template("patrols/all.html", patrols=Group.get_patrols())


@bp.route("/by-name/<name>")
def by_name(name):
    patrol = Group.named(name)
    ranks = [r for r in Rank.all() if not r.extra_rank]
    requirements = sorted([r for r in Requirement.all() if r.badge in ranks])
    return render_template(
        "patrols/patrol.html", patrol=patrol, requirements=requirements
    )

app/templates/patrols/all.html
{% extends 'base.html' %}

{% block title %}Patrols{% endblock %}

{% block content %}
    <table>
    {% for patrol in patrols %}
        <tr><th colspan=5><a href="{{url_for("patrols.by_name", name=patrol.name)}}">{{ patrol.name }}</a></th></tr>
        <tr>
            <th>Name</th>
            <th>Current Rank</th>
            <th>Rank Date</th>
            <th>Pct to next rank</th>
        </tr>
        {% for scout in patrol.members %}
        <tr>
            <td><a href="{{ url_for("scouts.by_id", id=scout.id)}}">{{scout.display_name}}</a></td>
            <td>{{scout.current_rank.name}}</td>
            <td>{{scout.current_rank_date}}</td>
            <td><div class="w3-light-grey">
                    <div class="w3-container w3-green w3-center" style="width:{{scout.pct_to_next_rank|round|int}}%">{{scout.pct_to_next_rank|round|int}}%</div>
                </div></td>
        </tr>
        {% endfor %}
    {% endfor %}
    </table>

{% endblock %}

app/templates/patrols/patrol.html
{% extends 'base.html' %}

{% block title %}{{ patrol.name }}{% endblock %}

{% block content %}
<table>
    <tr>
        <th><br></th>
        <th><br></th>
        <th colspan={{ patrol.members | count + 1}}>Scouts</th>
    </tr>
    <tr>
        <th>Rank</th>
        <th>Code</th>
        <th>Requirement</th>
        {% for scout in patrol.members %}
        <td><a href="{{ url_for("scouts.by_id", id=scout.id)}}">{{scout.display_name}}</a></td>
        {% endfor %}
    </tr>
    {% for requirement in requirements %}
    <tr>
        <td>{{ requirement.badge.name }}</td>
        <td>{{ requirement.shortcode }}</td>
        <td>{% include "advancement/requirement.html" %}</td>
        {% for scout in patrol.members %}
            <td>
            {% if scout.get_signoff(requirement.code).date %}
            {% include "check_boxes/checked.html" %}
            {% else %}
            {% include "check_boxes/unchecked.html" %}
            {% endif %}
            </td>
        {% endfor %}
    {% endfor %}
    </tr>
</table>
{% endblock %}