app/models/group.py
"""
group.py

"""
from app.extensions import db


class Group(db.Model):
    __tablename__ = "group"
    name = db.Column(db.String, primary_key=True)
    members = db.relationship("User", secondary="user_group", back_populates="groups")

    def __repr__(self):
        return f"<Group: {self.name}>"

    def __lt__(self, other):
        return self.name < other.name

    def __iter__(self):
        for member in self.members:
            yield member

    @classmethod
    def exists(cls, name):
        return bool(db.session.query(cls).filter(cls.name == name).one_or_none())

    @classmethod
    def get_group(cls, name):
        group = db.session.query(cls).filter(cls.name == name).one_or_none()
        if not group:
            group = cls(name=name)
            db.session.add(group)
        return group

    named = get_group

    @classmethod
    def all(cls):
        return db.session.query(cls).all()

    get_patrols = all


class UserGroup(db.Model):
    __tablename__ = "user_group"
    user_id = db.Column(db.Integer, db.ForeignKey("user.id"), primary_key=True)
    group_id = db.Column(db.String, db.ForeignKey("group.name"), primary_key=True)

app/blueprints/groups/__init__.py
from flask import Blueprint

bp = Blueprint("groups", __name__)

from app.blueprints.groups import routes

__all__ = [
    "bp",
    "routes",
]

app/blueprints/groups/routes.py
import urllib
from flask import render_template, request, flash, redirect, url_for
from flask_login import login_required
from app.blueprints.groups import bp
from app.extensions import db
from app.models import Group, User, Scout, Adult


@bp.route("/", methods=["GET"])
def all():
    groups = Group.all()
    return render_template("groups/all.html", groups=groups)


@login_required
@bp.route("/<string:group_name>/edit", methods=["PATCH"])
def edit(group_name):
    group = Group.named(urllib.parse.unquote(group_name))
    all_people = Scout.all() + Adult.all()
    return render_template("groups/one_group.html", group=group, users=all_people)


@login_required
@bp.route("/<string:group_name>/clone", methods=["POST"])
def clone(group_name):
    group = Group.named(urllib.parse.unquote(group_name))
    new_group_name = urllib.parse.unquote(request.headers.get("HX-Prompt"))
    if Group.exists(new_group_name):
        flash(f"group already exists with name {new_group_name}")
        return redirect(url_for("groups.all"))
    new_group = Group(name=new_group_name)
    new_group.members = group.members.copy()
    db.session.add(new_group)
    db.session.commit()
    return redirect(url_for("groups.all"))


@login_required
@bp.route("/<string:group_name>/delete", methods=["DELETE"])
def delete(group_name):
    group = Group.named(urllib.parse.unquote(group_name))
    del group
    db.session.commit()
    return "BALEETED"


@login_required
@bp.route("/add", methods=["PUT"])
def add():
    group_name = urllib.parse.unquote(request.headers.get("HX-Prompt"))
    if Group.exists(group_name):
        flash(f"group already exists with name {group_name}")
        return redirect(url_for("groups.all"))
    new_group = Group(name=group_name)
    db.session.add(new_group)
    db.session.commit()
    return redirect(url_for("groups.all"))


@login_required
@bp.route("/<string:group_name>/member_delete/<string:member_id>", methods=["DELETE"])
def member_delete(group_name, member_id):
    group = Group.named(urllib.parse.unquote(group_name))
    user = User.named(id=member_id)
    if user in group.members:
        group.members.remove(user)
        if hasattr(user, "patrol"):
            user.patrol = ""
        db.session.commit()
        return "DELETED"
    return "ERROR"


@login_required
@bp.route("/<string:group_name>/member_add/<string:user_id>", methods=["PUT"])
def member_add(group_name, user_id):
    group = Group.named(urllib.parse.unquote(group_name))
    user = User.named(id=user_id)
    group.members.append(user)
    db.session.commit()
    return ":thumbsup:"

app/templates/groups/all.html
{% extends 'base.html' %}

{% block title %}Groups{% endblock %}

{% block content %}
    <p hx-put={{url_for("groups.add")}} hx-prompt="Enter group name: ">ADD GROUP</p>
    <table>
    {% for group in groups %}
    <tr><td>{{ group.name }}</td>
        <td hx-patch={{url_for("groups.edit", group_name=group.name)}} hx-target="closest body">EDIT</td>
        <td hx-post={{url_for("groups.clone", group_name=group.name)}} hx-target="closest body" hx-prompt="Enter new group name: ">CLONE</td>
        <td hx-delete={{url_for("groups.delete", group_name=group.name)}} hx-confirm="Are you sure you want to delete {{group.name}}" hx-target="closest tr" hx-swap="innerHTML">DELETE</td>
    </tr>
    {% endfor %}
    </table>

{% endblock %}

app/templates/groups/one_group.html
{% extends 'base.html' %}

{% block title %}Edit {{group.name}}{% endblock %}

{% block content %}
    <p><a href={{url_for("groups.all")}}>Return to All Groups</a></p>
    <table>
    {% for member in group.members %}
    <tr><td>{{member.firstname }} {{ member.lastname }}</td>
        <td hx-delete={{url_for("groups.member_delete", group_name=group.name, member_id=member.id)}} hx-target="closest tr">REMOVE</td>
    </tr>
    {% endfor %}
    </table>
    <table>
    {% for user in users %}
    	{% if user in group.members %}
	{% else %}
    <tr><td>{{ user.firstname }} {{user.lastname}}</td>
        <td hx-put={{url_for("groups.member_add", group_name=group.name, user_id=user.id)}}>ADD</td>
    </tr>
    	{% endif %}
    {% endfor %}
    </table>

{% endblock %}